name: build_ErfanGSIs


on:
#  release:
#    types: [published]
  push:
     branches:
      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://doc-0s-54-docs.googleusercontent.com/docs/securesc/qhn4hof76gee37hmfke40vdslvqju941/j3ggtgmmqn59kjq52fvlfe3nt8f83n9v/1646589000000/08141801680995429494/16594940542488577672/1LEYqdSGK6jenO79yGtdnQyUfkE1gssLc?e=download&ax=ACxEAsYDzOqLNvbFTOkiZoRQM_CTuifckick37Xi-GhWb-WAS62xrk_Upt2nKCiRZytnhDA8guZlg8bV2pA8TwXRByZHfKV8R-UBFjo_pEeJ_V7KB9e0LJ_UfvzQKIeRzwJKO8zMGbZwVO8qwuzF3T4dBMk2lT-4wxjUJxh3rY7kh3MKj8b2c2Xh8iwYOWO3EPUPflc4VR7HMSwZ4DWhUJmLYNtfOyTPO0BFwwe4pFBvsTxvg3VuPtwndPSYROM7so7Ien2nyu9H7NkCUE-nlq7DbGMEPPMP4fH5F__EHRkrwhZHaGRsuYSBlEysm-fzLn1uR1m7byr76M2Sc5qpBJpCQB4zW8xoxSl8olSV2VWTDi4aUzOlz5d3DCkamRHEew56PC-bN_Zhd4bjF3QURfT_R2Svxx6UpTBIonQorsHTISIFtFxuZGBPw9WYn7xEnj0A7vVbQBCXO-NBCfpVuHoQy0IwG4Ln2zpEfH1lEltAuOi2rrxPJ5niQa3xg6R1GPuf68W_VWrJmL-gBawETzURhzOyGKhWSmLNYXs6l9Eu9dJ3M8yg1Fcx96_YOJdRy3wcCISu0Ae7zbq2Pq5u9jvfJMlegRpQbBfNtP_FPLBbq9XG3NaoXFUhkXjf2hlBL9jqGxFh_MlLEslISNkGnmo7AF4jR1PExzmZKYtTCgqi&authuser=0&nonce=i09fj2scnr3ts&user=16594940542488577672&hash=6cunmu8on8ab7hc7q7ihgc14eigm50nj
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
